---
# Playbook to start EpMon
#
- name: "Starting EpMon"
  hosts: "{{ epmons_group_name }}:!disabled"
  become: true
  tasks:
    - name: Start epmon
      ansible.builtin.service:
        name: "apimon-epmon"
        state: "started"
